/* books.js
   The real books customers buy. Two lists, combined at the bottom.

   FICTION: OCLC's WorldCat "Library 100: Top 500 Novels", the novels most widely
   held by libraries around the world, in rank order.
   https://www.oclc.org/en/worldcat/library100/top500.html
   Each entry is [title, author, genre]. The genre labels are OCLC's own
   ("action", "fantasy", "mystery", and so on; blank where they gave none).

   NONFICTION: the Guardian's "100 best nonfiction books of all time" (Robert
   McCrum, 2017), in the paper's order from newest to oldest.
   https://www.theguardian.com/books/2017/dec/31/the-100-best-nonfiction-books-of-all-time-the-full-list
   Each entry is [title, author, year]. Four titles are left out on purpose:
   the King James Bible, the Book of Common Prayer, Donne's Devotions Upon
   Emergent Occasions, and C S Lewis's A Grief Observed.
*/

const BOOKS = [
  ["Don Quixote", "Miguel de Cervantes", "action"],
  ["Alice's Adventures in Wonderland", "Lewis Carroll", "fantasy"],
  ["The Adventures of Huckleberry Finn", "Mark Twain", "action"],
  ["The Adventures of Tom Sawyer", "Mark Twain", "action"],
  ["Treasure Island", "Robert Louis Stevenson", "action"],
  ["Pride and Prejudice", "Jane Austen", "romance"],
  ["Wuthering Heights", "Emily Brontë", ""],
  ["Jane Eyre", "Charlotte Brontë", "romance"],
  ["Moby Dick", "Herman Melville", ""],
  ["The Scarlet Letter", "Nathaniel Hawthorne", ""],
  ["Gulliver's Travels", "Jonathan Swift", "fantasy"],
  ["The Pilgrim's Progress", "John Bunyan", "allegories"],
  ["A Christmas Carol", "Charles Dickens", ""],
  ["David Copperfield", "Charles Dickens", "bildung"],
  ["A Tale of Two Cities", "Charles Dickens", "history"],
  ["Little Women", "Louisa May Alcott", ""],
  ["Great Expectations", "Charles Dickens", "bildung"],
  ["The Hobbit, or, There and Back Again", "J.R.R. Tolkien", "fantasy"],
  ["Frankenstein, or, the Modern Prometheus", "Mary Shelley", "horror"],
  ["Oliver Twist", "Charles Dickens", "bildung"],
  ["Uncle Tom's Cabin", "Harriet Beecher Stowe", "political"],
  ["Crime and Punishment", "Fyodor Dostoyevsky", ""],
  ["Madame Bovary: Patterns of Provincial life", "Gustave Flaubert", ""],
  ["The Return of the King", "J.R.R. Tolkien", "fantasy"],
  ["Dracula", "Bram Stoker", ""],
  ["The Three Musketeers", "Alexandre Dumas", "history"],
  ["Brave New World", "Aldous Huxley", ""],
  ["War and Peace", "Leo Tolstoy", "history"],
  ["To Kill a Mockingbird", "Harper Lee", ""],
  ["The Wizard of Oz", "L. Frank Baum", "fantasy"],
  ["Les Misérables", "Victor Hugo", ""],
  ["The Secret Garden", "Frances Hodgson Burnett", ""],
  ["Animal Farm", "George Orwell", "political"],
  ["The Great Gatsby", "F. Scott Fitzgerald", ""],
  ["The Little Prince", "Antoine de Saint-Exupéry", ""],
  ["The Call of the Wild", "Jack London", "action"],
  ["20,000 Leagues Under the Sea", "Jules Verne", "scifi"],
  ["Anna Karenina", "Leo Tolstoy", "romance"],
  ["The Wind in the Willows", "Kenneth Grahame", "fantasy"],
  ["The Picture of Dorian Gray", "Oscar Wilde", ""],
  ["The Grapes of Wrath", "John Steinbeck", ""],
  ["Sense and Sensibility", "Jane Austen", "romance"],
  ["The Last of the Mohicans", "James Fenimore Cooper", "history"],
  ["Tess of the d'Urbervilles", "Thomas Hardy", ""],
  ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "fantasy"],
  ["Heidi", "Johanna Spyri", ""],
  ["Ulysses", "James Joyce", ""],
  ["The Complete Sherlock Holmes", "Arthur Conan Doyle", "mystery"],
  ["The Count of Monte Cristo", "Alexandre Dumas", "history"],
  ["The Old Man and the Sea", "Ernest Hemingway", "allegories"],
  ["The Lion, the Witch, and the Wardrobe", "C.S. Lewis", "fantasy"],
  ["The Hunchback of Notre Dame", "Victor Hugo", "history"],
  ["Pinocchio", "Carlo Collodi", ""],
  ["One Hundred Years of Solitude", "Gabriel García Márquez", ""],
  ["Ivanhoe", "Walter Scott", "history"],
  ["The Red Badge of Courage", "Stephen Crane", "history"],
  ["Anne of Green Gables", "L.M. Montgomery", ""],
  ["Black Beauty", "Anna Sewell", ""],
  ["Peter Pan", "J.M. Barrie", "fantasy"],
  ["A Farewell to Arms", "Ernest Hemingway", "war"],
  ["The House of the Seven Gables", "Nathaniel Hawthorne", ""],
  ["Lord of the Flies", "William Golding", ""],
  ["The Prince and the Pauper", "Mark Twain", "history"],
  ["A Portrait of the Artist as a Young Man", "James Joyce", "bildung"],
  ["Lord Jim", "Joseph Conrad", ""],
  ["Harry Potter and the Chamber of Secrets", "J.K. Rowling", "fantasy"],
  ["The Red & the Black", "Stendhal", "bildung"],
  ["The Stranger", "Albert Camus", ""],
  ["The Trial", "Franz Kafka", "allegories"],
  ["Lady Chatterley's Lover", "D.H. Lawrence", ""],
  ["Kidnapped: The Adventures of David Balfour", "Robert Louis Stevenson", "history"],
  ["The Catcher in the Rye", "J.D. Salinger", "bildung"],
  ["Fahrenheit 451", "Ray Bradbury", "scifi"],
  ["A Journey to the Center of the Earth", "Jules Verne", "scifi"],
  ["Vanity Fair", "William Makepeace Thackeray", ""],
  ["All Quiet on the Western Front", "Erich Maria Remarque", "war"],
  ["Gone with the Wind", "Margaret Mitchell", "history"],
  ["My Ántonia", "Willa Cather", ""],
  ["Of Mice and Men", "John Steinbeck", ""],
  ["The Vicar of Wakefield", "Oliver Goldsmith", ""],
  ["A Connecticut Yankee in King Arthur's Court", "Mark Twain", "fantasy"],
  ["White Fang", "Jack London", "action"],
  ["Fathers and Sons", "Ivan Sergeevich Turgenev", ""],
  ["Doctor Zhivago", "Boris Leonidovich Pasternak", "history"],
  ["The Decameron", "Giovanni Boccaccio", ""],
  ["Nineteen Eighty-Four", "George Orwell", "political"],
  ["The Jungle", "Upton Sinclair", "political"],
  ["The Da Vinci Code", "Dan Brown", "mystery"],
  ["Persuasion", "Jane Austen", "romance"],
  ["Mansfield Park", "Jane Austen", "romance"],
  ["Candide", "Voltaire", ""],
  ["For Whom the Bell Tolls", "Ernest Hemingway", "war"],
  ["Far from the Madding Crowd", "Thomas Hardy", "romance"],
  ["The Fellowship of the Ring", "J.R.R. Tolkien", "fantasy"],
  ["The Return of the Native", "Thomas Hardy", "romance"],
  ["Sons and Lovers", "D.H. Lawrence", ""],
  ["Charlotte's Web", "E.B. White", "fantasy"],
  ["The Swiss Family Robinson", "Johann David Wyss", ""],
  ["Bleak House", "Charles Dickens", ""],
  ["Père Goriot", "Honoré de Balzac", "bildung"],
  ["Utopia", "Thomas More", ""],
  ["The History of Tom Jones, a Foundling", "Henry Fielding", ""],
  ["Harry Potter and the Prisoner of Azkaban", "J.K. Rowling", "fantasy"],
  ["Kim", "Rudyard Kipling", "action"],
  ["The Sound and the Fury", "William Faulkner", ""],
  ["Harry Potter and the Goblet of Fire", "J.K. Rowling", "fantasy"],
  ["The Mill on the Floss", "George Eliot", ""],
  ["A Wrinkle in Time", "Madeleine L'Engle", "scifi"],
  ["The Hound of the Baskervilles", "Arthur Conan Doyle", "mystery"],
  ["The Two Towers", "J.R.R. Tolkien", "fantasy"],
  ["The War of the Worlds", "H.G. Wells", "scifi"],
  ["Middlemarch", "George Eliot", ""],
  ["The Age of Innocence", "Edith Wharton", ""],
  ["The Color Purple", "Alice Walker", ""],
  ["Northanger Abbey", "Jane Austen", "romance"],
  ["East of Eden", "John Steinbeck", ""],
  ["On the Road", "Jack Kerouac", "autobio"],
  ["Catch-22", "Joseph Heller", "war"],
  ["Around the World in Eighty Days", "Jules Verne", "action"],
  ["Hard Times", "Charles Dickens", ""],
  ["Beloved", "Toni Morrison", "history"],
  ["Mrs. Dalloway", "Virginia Woolf", ""],
  ["To the Lighthouse", "Virginia Woolf", ""],
  ["The Magician's Nephew", "C.S. Lewis", "fantasy"],
  ["Harry Potter and the Order of the Phoenix", "J.K. Rowling", "fantasy"],
  ["The Sun Also Rises", "Ernest Hemingway", "history"],
  ["The Good Earth", "Pearl S. Buck", ""],
  ["Silas Marner", "George Eliot", ""],
  ["Love in the Time of Cholera", "Gabriel García Márquez", "romance"],
  ["Rebecca", "Daphne Du Maurier", "romance"],
  ["Jude the Obscure", "Thomas Hardy", ""],
  ["Twilight", "Stephenie Meyer", "romance"],
  ["A Passage to India", "E.M. Forster", "political"],
  ["The Plague", "Albert Camus", ""],
  ["Nicholas Nickleby", "Charles Dickens", "bildung"],
  ["The Pearl", "John Steinbeck", ""],
  ["Ethan Frome", "Edith Wharton", ""],
  ["The Tale of Genji", "Murasaki Shikibu", ""],
  ["The Giver", "Lois Lowry", "scifi"],
  ["The Alchemist", "Paulo Coelho", ""],
  ["The Strange Case of Dr. Jekyll and Mr. Hyde", "Robert Louis Stevenson", ""],
  ["Robinson Crusoe", "Daniel Defoe", "action"],
  ["Tender is the Night", "F. Scott Fitzgerald", ""],
  ["The Idiot", "Fyodor Dostoyevsky", "history"],
  ["Hatchet", "Gary Paulsen", "action"],
  ["The Kite Runner", "Khaled Hosseini", "bildung"],
  ["One Flew Over the Cuckoo's Nest", "Ken Kesey", ""],
  ["The Portrait of a Lady", "Henry James", ""],
  ["The Outsiders", "S.E. Hinton", ""],
  ["Ben-Hur", "Lew Wallace", "history"],
  ["The Mayor of Casterbridge", "Thomas Hardy", ""],
  ["Cry, The Beloved Country", "Alan Paton", "political"],
  ["The Last Battle", "C.S. Lewis", "fantasy"],
  ["Captains Courageous", "Rudyard Kipling", "bildung"],
  ["The Castle", "Franz Kafka", "allegories"],
  ["The Metamorphosis", "Franz Kafka", ""],
  ["The Magic Mountain (Der Zauberberg)", "Thomas Mann", "bildung"],
  ["James and the Giant Peach", "Roald Dahl", ""],
  ["The Horse and His Boy", "C.S. Lewis", "fantasy"],
  ["Angels & Demons", "Dan Brown", "thrillers"],
  ["The Voyage of the Dawn Treader", "C.S. Lewis", "fantasy"],
  ["The Bell Jar", "Sylvia Plath", ""],
  ["Women in Love", "D.H. Lawrence", ""],
  ["The Yearling", "Marjorie Kinnan Rawlings", ""],
  ["O Pioneers!", "Willa Cather", ""],
  ["The Handmaid's Tale", "Margaret Atwood", ""],
  ["The Moonstone", "Wilkie Collins", "mystery"],
  ["The Old Curiosity Shop", "Charles Dickens", ""],
  ["Little Dorrit", "Charles Dickens", ""],
  ["Prince Caspian: The Return to Narnia", "C.S. Lewis", "fantasy"],
  ["Sister Carrie", "Theodore Dreiser", ""],
  ["The Silver Chair", "C.S. Lewis", "fantasy"],
  ["The Hunger Games", "Suzanne Collins", "scifi"],
  ["This Side of Paradise", "F. Scott Fitzgerald", "bildung"],
  ["Eugénie Grandet", "Honoré de Balzac", "allegories"],
  ["Of Human Bondage", "W. Somerset Maugham", "bildung"],
  ["Dream of the Red Chamber", "Cao Xueqin", ""],
  ["Life of Pi", "Yann Martel", ""],
  ["Harry Potter and the Deathly Hallows", "J.K. Rowling", "fantasy"],
  ["Invisible Man", "Ralph Ellison", ""],
  ["Steppenwolf", "Hermann Hesse", ""],
  ["The Sorrows of Young Werther", "Johann Wolfgang von Goethe", "autobio"],
  ["Bridge to Terabithia", "Katherine Paterson", "fantasy"],
  ["The Invisible Man", "H.G. Wells", ""],
  ["Holes", "Louis Sachar", ""],
  ["Siddhartha", "Hermann Hesse", ""],
  ["A Tree Grows in Brooklyn", "Betty Smith", ""],
  ["Through the Looking-Glass, and What Alice Found There", "Lewis Carroll", "fantasy"],
  ["In Cold Blood", "Truman Capote", ""],
  ["The House of the Spirits", "Isabel Allende", ""],
  ["Adam Bede", "George Eliot", "romance"],
  ["The Betrothed", "Alessandro Manzoni", "history"],
  ["The Book Thief", "Markus Zusak", "history"],
  ["Their Eyes Were Watching God", "Zora Neale Hurston", ""],
  ["One Day in the Life of Ivan Denisovich", "Aleksandr Isaevich Solzhenitsyn", ""],
  ["The Sea Wolf", "Jack London", ""],
  ["Catching Fire", "Suzanne Collins", "scifi"],
  ["Roll of Thunder, Hear My Cry", "Mildred D. Taylor", "history"],
  ["Death Comes for the Archbishop", "Willa Cather", "history"],
  ["The House of Mirth", "Edith Wharton", ""],
  ["Light in August", "William Faulkner", ""],
  ["The Pickwick Papers", "Charles Dickens", ""],
  ["Remembrance of Things Past", "Marcel Proust", "autobio"],
  ["Barchester Towers and the Warden", "Anthony Trollope", ""],
  ["The Bridge of San Luis Rey", "Thornton Wilder", "history"],
  ["The Help", "Kathryn Stockett", "history"],
  ["Murder on the Orient Express", "Agatha Christie", "mystery"],
  ["The Lovely Bones", "Alice Sebold", ""],
  ["The Appeal", "John Grisham", ""],
  ["Dombey And Son", "Charles Dickens", ""],
  ["Slaughterhouse-Five", "Kurt Vonnegut", "scifi"],
  ["An American Tragedy", "Theodore Dreiser", "romance"],
  ["The Bluest Eye", "Toni Morrison", "bildung"],
  ["Little House In the Big Woods", "Laura Ingalls Wilder", "history"],
  ["Pippi Longstocking", "Astrid Lindgren", ""],
  ["Germinal", "Émile Zola", "political"],
  ["The Heart Is a Lonely Hunter", "Carson McCullers", ""],
  ["The Woman In White", "Wilkie Collins", ""],
  ["Absalom, Absalom!", "William Faulkner", ""],
  ["A Painted House", "John Grisham", ""],
  ["The Girl With the Dragon Tattoo", "Stieg Larsson", "thrillers"],
  ["A Room With a View", "E.M. Forster", ""],
  ["Watership Down", "Richard Adams", "allegories"],
  ["Memoirs of a Geisha", "Arthur Golden", "history"],
  ["Our Mutual Friend", "Charles Dickens", "romance"],
  ["Babbitt", "Sinclair Lewis", ""],
  ["The Red Pony", "John Steinbeck", "bildung"],
  ["All the King's Men", "Robert Penn Warren", "political"],
  ["Things Fall Apart", "Chinua Achebe", "history"],
  ["Lorna Doone", "R.D. Blackmore", "history"],
  ["Johnny Tremain", "Esther Forbes", "history"],
  ["Anne of Avonlea", "L.M. Montgomery", ""],
  ["Tuck Everlasting", "Natalie Babbitt", "fantasy"],
  ["The BFG", "Roald Dahl", ""],
  ["Cannery Row", "John Steinbeck", "romance"],
  ["The Joy Luck Club", "Amy Tan", ""],
  ["The Silmarillion", "J.R.R. Tolkien", "fantasy"],
  ["Roots", "Alex Haley", ""],
  ["Little House on the Prairie", "Laura Ingalls Wilder", "autobio"],
  ["Native Son", "Richard Wright", ""],
  ["Stuart Little", "E.B. White", "action"],
  ["Cross Fire", "James Patterson", ""],
  ["The Power and the Glory", "Graham Greene", "mystery"],
  ["A Clockwork Orange", "Anthony Burgess", "scifi"],
  ["The Phantom of the Opera", "Gaston Leroux", "horror"],
  ["The Martian Chronicles", "Ray Bradbury", "scifi"],
  ["The Road", "Cormac McCarthy", ""],
  ["The Way of All Flesh", "Samuel Butler", ""],
  ["Diary of a Wimpy Kid: The Long Haul", "Jeff Kinney", ""],
  ["Villette", "Charlotte Brontë", ""],
  ["The Curious Incident of the Dog In the Night-Time", "Mark Haddon", "mystery"],
  ["The Mysterious Island", "Jules Verne", "scifi"],
  ["Song of Solomon", "Toni Morrison", ""],
  ["Nana", "Émile Zola", ""],
  ["Quo Vadis", "Henryk Sienkiewicz", "history"],
  ["Main Street", "Sinclair Lewis", ""],
  ["Matilda", "Roald Dahl", ""],
  ["Lolita", "Vladimir Vladimirovich Nabokov", "romance"],
  ["Paper Towns", "John Green", "bildung"],
  ["Sounder", "William H. Armstrong", ""],
  ["Are You There God? It's Me, Margaret", "Judy Blume", ""],
  ["The Notebook", "Nicholas Sparks", "romance"],
  ["From the Mixed-Up Files of Mrs. Basil E. Frankweiler", "E.L. Konigsburg", ""],
  ["Atlas Shrugged", "Ayn Rand", "scifi"],
  ["The Fountainhead", "Ayn Rand", ""],
  ["Number the Stars", "Lois Lowry", "history"],
  ["The Firm", "John Grisham", ""],
  ["Swann's Way", "Marcel Proust", "autobio"],
  ["Ender's Game", "Orson Scott Card", "scifi"],
  ["The Name of the Rose", "Umberto Eco", "history"],
  ["A Time to Kill", "John Grisham", ""],
  ["Water for Elephants", "Sara Gruen", "romance"],
  ["The Time Machine", "H.G. Wells", "scifi"],
  ["Eragon", "Christopher Paolini", "fantasy"],
  ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "scifi"],
  ["Buddenbrooks", "Thomas Mann", ""],
  ["A Thousand Splendid Suns", "Khaled Hosseini", ""],
  ["The Witch of Blackbird Pond", "Elizabeth George Speare", ""],
  ["And Then There Were None", "Agatha Christie", "mystery"],
  ["A Separate Peace", "John Knowles", "history"],
  ["Breaking Dawn", "Stephenie Meyer", "romance"],
  ["As I Lay Dying", "William Faulkner", ""],
  ["The Girl Who Played With Fire", "Stieg Larsson", "thrillers"],
  ["Where the Red Fern Grows", "Wilson Rawls", "bildung"],
  ["Le Morte D'Arthur", "Thomas Malory", ""],
  ["Mockingjay", "Suzanne Collins", "scifi"],
  ["The Pillars of the Earth", "Ken Follett", "history"],
  ["Persian Letters", "Montesquieu", ""],
  ["The Client", "John Grisham", ""],
  ["Sula", "Toni Morrison", ""],
  ["Tales of a Fourth Grade Nothing", "Judy Blume", ""],
  ["The Merry Adventures of Robin Hood of Great Renown In Nottinghamshire", "Howard Pyle", ""],
  ["Tortilla Flat", "John Steinbeck", ""],
  ["Look Homeward, Angel", "Thomas Wolfe", ""],
  ["The Mystery of Edwin Drood", "Charles Dickens", ""],
  ["Brideshead Revisited", "Evelyn Waugh", ""],
  ["The Pelican Brief", "John Grisham", "mystery"],
  ["Atonement", "Ian McEwan", ""],
  ["Washington Square", "Henry James", ""],
  ["Like Water for Chocolate", "Laura Esquivel", "romance"],
  ["The Golden Compass", "Philip Pullman", ""],
  ["The Secret Life of Bees", "Sue Monk Kidd", ""],
  ["The Fault In Our Stars", "John Green", "romance"],
  ["Nostromo", "Joseph Conrad", "political"],
  ["Finnegans Wake", "James Joyce", ""],
  ["The Brethren", "John Grisham", "thrillers"],
  ["Coraline", "Neil Gaiman", ""],
  ["Heart of Darkness", "Joseph Conrad", ""],
  ["On the Banks of Plum Creek", "Laura Ingalls Wilder", "autobio"],
  ["Rebecca of Sunnybrook Farm", "Kate Douglas Smith Wiggin", ""],
  ["The Ambassadors", "Henry James", ""],
  ["The Secret Agent", "Joseph Conrad", "political"],
  ["The House on Mango Street", "Sandra Cisneros", "bildung"],
  ["Go Tell It on the Mountain", "James Baldwin", "bildung"],
  ["The Testament", "John Grisham", "thrillers"],
  ["The Clan of the Cave Bear", "Jean M. Auel", "history"],
  ["Cranford", "Elizabeth Cleghorn Gaskell", ""],
  ["Because of Winn-Dixie", "Kate DiCamillo", ""],
  ["My Side of the Mountain", "Jean Craighead George", ""],
  ["The Runaway Jury", "John Grisham", "thrillers"],
  ["The Mouse and the Motorcycle", "Beverly Cleary", ""],
  ["The Lost Symbol", "Dan Brown", "thrillers"],
  ["The Forsyte Saga", "John Galsworthy", ""],
  ["Gone Girl", "Gillian Flynn", "thrillers"],
  ["The Lightning Thief", "Rick Riordan", "fantasy"],
  ["The Last Days of Pompeii", "Edward Bulwer Lytton", "history"],
  ["The Reader", "Bernhard Schlink", ""],
  ["Caddie Woodlawn", "Carol Ryrie Brink", ""],
  ["The Tale of Despereaux", "Kate DiCamillo", ""],
  ["The Girl Who Kicked the Hornet's Nest", "Stieg Larsson", "thrillers"],
  ["Dear Mr. Henshaw", "Beverly Cleary", ""],
  ["The Killer Angels", "Michael Shaara", "history"],
  ["Chronicle of a Death Foretold", "Gabriel García Márquez", ""],
  ["The Five People You Meet In Heaven", "Mitch Albom", ""],
  ["The Master and Margarita", "Mikhail Bulgakov", "political"],
  ["Winesburg, Ohio", "Sherwood Anderson", ""],
  ["\"P\" Is for Peril", "Sue Grafton", "mystery"],
  ["My Sister's Keeper", "Jodi Picoult", ""],
  ["Barnaby Rudge", "Charles Dickens", "political"],
  ["Howards End", "E.M. Forster", ""],
  ["The Broker", "John Grisham", "thrillers"],
  ["The Camel Club", "David Baldacci", "political"],
  ["The Rainbow", "D.H. Lawrence", ""],
  ["The Man In the Iron Mask", "Alexandre Dumas", "history"],
  ["Mary Poppins", "P.L. Travers", "fantasy"],
  ["Artemis Fowl", "Eoin Colfer", "fantasy"],
  ["Dear John", "Nicholas Sparks", "romance"],
  ["Cold Mountain", "Charles Frazier", "romance"],
  ["Flowers for Algernon", "Daniel Keyes", ""],
  ["The Dark Is Rising", "Susan Cooper", "fantasy"],
  ["Resurrection", "Leo Tolstoy", ""],
  ["Fearless Fourteen", "Janet Evanovich", "mystery"],
  ["A Sentimental Journey Through France and Italy", "Laurence Sterne", ""],
  ["The King of Torts", "John Grisham", "thrillers"],
  ["The Graveyard Book", "Neil Gaiman", ""],
  ["The Quiet American", "Graham Greene", "political"],
  ["The Chamber", "John Grisham", ""],
  ["The English Patient", "Michael Ondaatje", "history"],
  ["Snow Falling on Cedars", "David Guterson", ""],
  ["The Long Winter", "Laura Ingalls Wilder", "autobio"],
  ["Sarah, Plain and Tall", "Patricia MacLachlan", ""],
  ["Cross Country", "James Patterson", "thrillers"],
  ["The Spy Who Came In from the Cold", "John Le Carré", ""],
  ["A Game of Thrones", "George R.R. Martin", "fantasy"],
  ["The Thorn Birds", "Colleen McCullough", ""],
  ["Old Yeller", "Fred Gipson", "bildung"],
  ["Ramona Quimby, Age 8", "Beverly Cleary", ""],
  ["Death In Venice", "Thomas Mann", ""],
  ["By the Shores of Silver Lake", "Laura Ingalls Wilder", "autobio"],
  ["Inferno", "Dan Brown", "thrillers"],
  ["Schindler's List", "Thomas Keneally", ""],
  ["Jonathan Livingston Seagull", "Richard Bach", "allegories"],
  ["The Stand", "Stephen King", "horror"],
  ["The Last Juror", "John Grisham", "thrillers"],
  ["Shiloh", "Phyllis Reynolds Naylor", ""],
  ["Girl With a Pearl Earring", "Tracy Chevalier", ""],
  ["The Murder of Roger Ackroyd", "Agatha Christie", "mystery"],
  ["It", "Stephen King", "horror"],
  ["The Rainmaker", "John Grisham", ""],
  ["The Poisonwood Bible", "Barbara Kingsolver", ""],
  ["The Indian in the Cupboard", "Lynne Reid Banks", "fantasy"],
  ["The Maltese Falcon", "Dashiell Hammett", "mystery"],
  ["The Warden", "Anthony Trollope", ""],
  ["The Summons", "John Grisham", "thrillers"],
  ["Encyclopedia Brown: Boy Detective", "Donald J. Sobol", "mystery"],
  ["The Time Traveler's Wife", "Audrey Niffenegger", ""],
  ["The Incredible Journey", "Sheila Burnford", "action"],
  ["Daughter of Fortune", "Isabel Allende", "romance"],
  ["Shirley", "Charlotte Brontë", "history"],
  ["Bud, Not Buddy", "Christopher Paul Curtis", "history"],
  ["The Horse Whisperer", "Nicholas Evans", ""],
  ["The Street Lawyer", "John Grisham", "thrillers"],
  ["Nausea", "Jean-Paul Sartre", ""],
  ["To Have and Have Not", "Ernest Hemingway", "action"],
  ["The Bridges of Madison County", "Robert James Waller", "romance"],
  ["Anne of the Island", "L.M. Montgomery", ""],
  ["The Winter of Our Discontent", "John Steinbeck", ""],
  ["The Shining", "Stephen King", "horror"],
  ["The Tenant of Wildfell Hall", "Anne Brontë", ""],
  ["First Family", "David Baldacci", "thrillers"],
  ["The Partner", "John Grisham", "thrillers"],
  ["The Girl on the Train", "Paula Hawkins", ""],
  ["The Black Arrow: A Tale of the Two Roses", "Robert Louis Stevenson", "history"],
  ["The Rise of Silas Lapham", "William Dea Howells", ""],
  ["The Choice", "Nicholas Sparks", "romance"],
  ["The Virginian: A Horseman of the Plains", "Owen Wister", ""],
  ["A Walk to Remember", "Nicholas Sparks", "romance"],
  ["The Maze Runner", "James Dashner", "scifi"],
  ["The Westing Game", "Ellen Raskin", "mystery"],
  ["Misty of Chincoteague", "Marguerite Henry", ""],
  ["Diary of a Wimpy Kid: The Last Straw", "Jeff Kinney", ""],
  ["King Solomon's Mines", "H. Rider Haggard", "action"],
  ["The Princess of Cleves", "Madame de (Marie-Madeleine Pioche de La Vergne) La Fayett", ""],
  ["Jacob Have I Loved", "Katherine Paterson", ""],
  ["Mrs. Frisby and the Rats of NIMH", "Robert C. O'Brien", "fantasy"],
  ["Misery", "Stephen King", "horror"],
  ["The Cider House Rules", "John Irving", "bildung"],
  ["King of the Wind", "Marguerite Henry", "history"],
  ["The Once and Future King", "T. H. White", "fantasy"],
  ["The Witches", "Roald Dahl", ""],
  ["The Subtle Knife", "Philip Pullman", "fantasy"],
  ["When You Reach Me", "Rebecca Stead", ""],
  ["Carrie", "Stephen King", "horror"],
  ["The Moon and Sixpence", "W. Somerset Maugham", ""],
  ["The Higher Power of Lucky", "Susan Patron", ""],
  ["Looking Backward, 2000-1887", "Edward Bellamy", ""],
  ["The Wings of the Dove", "Henry James", "romance"],
  ["The Summer of the Swans", "Betsy Cromer Byars", ""],
  ["Dangerous Liaisons", "Choderlos de Laclos", ""],
  ["Jurassic Park", "Michael Crichton", "scifi"],
  ["The Absolutely True Diary of a Part-time Indian", "Sherman Alexie", ""],
  ["The Grey King", "Susan Cooper", "fantasy"],
  ["The Leopard", "Giuseppe Tomasi di Lampedusa", "history"],
  ["The Mammoth Hunters", "Jean M. Auel", "history"],
  ["The Trumpet of the Swan", "E.B. White", "fantasy"],
  ["The Lucky One", "Nicholas Sparks", "romance"],
  ["These Happy Golden Years", "Laura Ingalls Wilder", "history"],
  ["Arrowsmith", "Sinclair Lewis", ""],
  ["Julie of the Wolves", "Jean Craighead George", "action"],
  ["The Screwtape Letters", "C.S. Lewis", ""],
  ["The Fall", "Albert Camus", ""],
  ["The No. 1 Ladies' Detective Agency", "Alexander McCall Smith", "mystery"],
  ["Worst Case", "James Patterson", "thrillers"],
  ["Lost Horizon", "James Hilton", "fantasy"],
  ["The Gunslinger", "Stephen King", "fantasy"],
  ["The Slave Dancer", "Paula Fox", "history"],
  ["Harry Potter and the Half-Blood Prince", "J.K. Rowling", "fantasy"],
  ["Inkheart", "Cornelia Funke", "fantasy"],
  ["Ramona and her Father", "Beverly Cleary", ""],
  ["Inkspell", "Cornelia Funke", "fantasy"],
  ["Ramona the Pest", "Beverly Cleary", ""],
  ["Walk Two Moons", "Sharon Creech", "bildung"],
  ["Miss Peregrine's Home for Peculiar Children", "Ransom Riggs", ""],
  ["The Chocolate War", "Robert Cormier", "bildung"],
  ["Sophie's Choice", "William Styron", "bildung"],
  ["Looking for Alaska", "John Green", "bildung"],
  ["Breakfast at Tiffany's", "Truman Capote", ""],
  ["The Razor's Edge", "W. Somerset Maugham", "bildung"],
  ["Dreamcatcher", "Stephen King", "horror"],
  ["Orlando", "Virginia Woolf", "history"],
  ["The Things they Carried", "Tim O'Brien", ""],
  ["Little Town on the Prairie", "Laura Ingalls Wilder", "history"],
  ["Nights in Rodanthe", "Nicholas Sparks", "romance"],
  ["The Amber Spyglass", "Philip Pullman", "fantasy"],
  ["The Miraculous Journey of Edward Tulane", "Kate DiCamillo", ""],
  ["Flatland", "Edwin A. Abbott", ""],
  ["Diary of a Wimpy Kid", "Jeff Kinney", ""],
  ["The Memory Keeper's Daughter", "Kim Edwards", ""],
  ["The Wedding", "Nicholas Sparks", "romance"],
  ["Fried Green Tomatoes at the Whistle-Stop Cafe", "Fannie Flagg", ""],
  ["The Cricket in Times Square", "George Selden", ""],
  ["The Phantom Tollbooth", "Norton Juster", "fantasy"],
  ["Rob Roy", "Walter Scott", "history"],
  ["The Death of Ivan Ilych", "Leo Tolstoy", ""],
  ["Alex Cross's Trial", "James Patterson", "thrillers"],
  ["Kenilworth", "Walter Scott", "history"],
  ["The Life and Opinions of Tristram Shandy", "Laurence Sterne", ""],
  ["The Remains of theDay", "Kazuo Ishiguro", "history"],
  ["M.C. Higgins, The Great", "Virginia Hamilton", "bildung"],
  ["Call It Courage", "Armstrong Sperry", "history"],
  ["Go Set a Watchman", "Harper Lee", ""],
  ["Bleachers", "John Grisham", ""],
  ["Elijah of Buxton", "Christopher Paul Curtis", ""],
  ["Swimsuit", "James Patterson", "mystery"],
  ["Cat's Cradle", "Kurt Vonnegut", "scifi"],
  ["The Caine Mutiny", "Herman Wouk", ""],
  ["The Heart of the Matter", "Graham Greene", ""],
  ["Harriet, the Spy", "Louise Fitzhugh", "mystery"],
  ["Darkness at Noon", "Arthur Koestler", "history"],
  ["A Prayer for Owen Meany", "John Irving", ""],
  ["The God of Small Things", "Arundhati Roy", ""],
  ["The Associate", "John Grisham", "thrillers"],
  ["The Shack", "William P. Young", ""],
  ["The Naked and the Dead", "Norman Mailer", "history"],
  ["The Sea of Monsters", "Rick Riordan", "fantasy"],
  ["Stranger in a Strange Land", "Robert A. Heinlein", "scifi"],
  ["Vision in White", "Nora Roberts", "romance"],
  ["The Whipping Boy", "Sid Fleischman", "action"],
  ["Room", "Emma Donoghue", ""],
  ["Deception Point", "Dan Brown", "political"],
].map(([title, author, genre]) => ({ title, author, genre, type: 'fiction' }));

const NONFICTION = [
  ["The Sixth Extinction", "Elizabeth Kolbert", "2014"],
  ["The Year of Magical Thinking", "Joan Didion", "2005"],
  ["No Logo", "Naomi Klein", "1999"],
  ["Birthday Letters", "Ted Hughes", "1998"],
  ["Dreams from My Father", "Barack Obama", "1995"],
  ["A Brief History of Time", "Stephen Hawking", "1988"],
  ["The Right Stuff", "Tom Wolfe", "1979"],
  ["Orientalism", "Edward Said", "1978"],
  ["Dispatches", "Michael Herr", "1977"],
  ["The Selfish Gene", "Richard Dawkins", "1976"],
  ["North", "Seamus Heaney", "1975"],
  ["Awakenings", "Oliver Sacks", "1973"],
  ["The Female Eunuch", "Germaine Greer", "1970"],
  ["Awopbopaloobop Alopbamboom", "Nik Cohn", "1969"],
  ["The Double Helix", "James D Watson", "1968"],
  ["Against Interpretation", "Susan Sontag", "1966"],
  ["Ariel", "Sylvia Plath", "1965"],
  ["The Feminine Mystique", "Betty Friedan", "1963"],
  ["The Making of the English Working Class", "EP Thompson", "1963"],
  ["Silent Spring", "Rachel Carson", "1962"],
  ["The Structure of Scientific Revolutions", "Thomas S Kuhn", "1962"],
  ["The Elements of Style", "William Strunk and EB White", "1959"],
  ["The Affluent Society", "John Kenneth Galbraith", "1958"],
  ["The Uses of Literacy: Aspects of Working-Class Life", "Richard Hoggart", "1957"],
  ["Notes of a Native Son", "James Baldwin", "1955"],
  ["The Nude: A Study of Ideal Art", "Kenneth Clark", "1956"],
  ["The Hedgehog and the Fox", "Isaiah Berlin", "1953"],
  ["Waiting for Godot", "Samuel Beckett", "1952/53"],
  ["A Book of Mediterranean Food", "Elizabeth David", "1950"],
  ["The Great Tradition", "FR Leavis", "1948"],
  ["The Last Days of Hitler", "Hugh Trevor-Roper", "1947"],
  ["The Common Sense Book of Baby and Child Care", "Dr Benjamin Spock", "1946"],
  ["Hiroshima", "John Hersey", "1946"],
  ["The Open Society and Its Enemies", "Karl Popper", "1945"],
  ["Black Boy: A Record of Childhood and Youth", "Richard Wright", "1945"],
  ["How to Cook a Wolf", "MFK Fisher", "1942"],
  ["Enemies of Promise", "Cyril Connolly", "1938"],
  ["The Road to Wigan Pier", "George Orwell", "1937"],
  ["The Road to Oxiana", "Robert Byron", "1937"],
  ["How to Win Friends and Influence People", "Dale Carnegie", "1936"],
  ["Testament of Youth", "Vera Brittain", "1933"],
  ["My Early Life: A Roving Commission", "Winston Churchill", "1930"],
  ["Goodbye to All That", "Robert Graves", "1929"],
  ["A Room of One’s Own", "Virginia Woolf", "1929"],
  ["The Waste Land", "TS Eliot", "1922"],
  ["Ten Days That Shook the World", "John Reed", "1919"],
  ["The Economic Consequences of the Peace", "John Maynard Keynes", "1919"],
  ["The American Language", "HL Mencken", "1919"],
  ["Eminent Victorians", "Lytton Strachey", "1918"],
  ["The Souls of Black Folk", "WEB Du Bois", "1903"],
  ["De Profundis", "Oscar Wilde", "1905"],
  ["The Varieties of Religious Experience", "William James", "1902"],
  ["Brief Lives", "John Aubrey", "1898"],
  ["Personal Memoirs", "Ulysses S Grant", "1885"],
  ["Life on the Mississippi", "Mark Twain", "1883"],
  ["Travels With a Donkey in the Cévennes", "Robert Louis Stevenson", "1879"],
  ["Nonsense Songs", "Edward Lear", "1871"],
  ["Culture and Anarchy", "Matthew Arnold", "1869"],
  ["On the Origin of Species", "Charles Darwin", "1859"],
  ["On Liberty", "John Stuart Mill", "1859"],
  ["The Wonderful Adventures of Mrs Seacole in Many Lands", "Mary Seacole", "1857"],
  ["The Life of Charlotte Brontë", "Elizabeth Gaskell", "1857"],
  ["Walden", "Henry David Thoreau", "1854"],
  ["Roget’s Thesaurus", "Peter Mark Roget", "1852"],
  ["London Labour and the London Poor", "Henry Mayhew", "1851"],
  ["Household Education", "Harriet Martineau", "1848"],
  ["Narrative of the Life of Frederick Douglass, an American Slave", "Frederick Douglass", "1845"],
  ["Essays", "RW Emerson", "1841"],
  ["Domestic Manners of the Americans", "Frances Trollope", "1832"],
  ["An American Dictionary of the English Language", "Noah Webster", "1828"],
  ["Confessions of an English Opium-Eater", "Thomas De Quincey", "1822"],
  ["Tales from Shakespeare", "Charles and Mary Lamb", "1807"],
  ["Travels in the Interior Districts of Africa", "Mungo Park", "1799"],
  ["The Autobiography of Benjamin Franklin", "Benjamin Franklin", "1793"],
  ["A Vindication of the Rights of Woman", "Mary Wollstonecraft", "1792"],
  ["The Life of Samuel Johnson LLD", "James Boswell", "1791"],
  ["Reflections on the Revolution in France", "Edmund Burke", "1790"],
  ["The Interesting Narrative of the Life of Olaudah Equiano", "Olaudah Equiano", "1789"],
  ["The Natural History and Antiquities of Selborne", "Gilbert White", "1789"],
  ["The Federalist Papers", "Alexander Hamilton, James Madison and John Jay", "1788"],
  ["The Diary of Fanny Burney", "Fanny Burney", "1778"],
  ["The History of the Decline and Fall of the Roman Empire", "Edward Gibbon", "1776-1788"],
  ["The Wealth of Nations", "Adam Smith", "1776"],
  ["Common Sense", "Tom Paine", "1776"],
  ["A Dictionary of the English Language", "Samuel Johnson", "1755"],
  ["A Treatise of Human Nature", "David Hume", "1739"],
  ["A Modest Proposal", "Jonathan Swift", "1729"],
  ["A Tour Through the Whole Island of Great Britain", "Daniel Defoe", "1727"],
  ["An Essay Concerning Human Understanding", "John Locke", "1689"],
  ["The Diary of Samuel Pepys", "Samuel Pepys", "1660"],
  ["Hydriotaphia, Urn Burial, or A Brief Discourse of the Sepulchral Urns Lately Found in Norfolk", "Sir Thomas Browne", "1658"],
  ["Leviathan", "Thomas Hobbes", "1651"],
  ["Areopagitica", "John Milton", "1644"],
  ["The First Folio", "William Shakespeare", "1623"],
  ["The Anatomy of Melancholy", "Robert Burton", "1621"],
  ["The History of the World", "Walter Raleigh", "1614"],
].map(([title, author, year]) => ({ title, author, year, genre: 'nonfiction', type: 'nonfiction' }));

// What customers actually pick from. Fiction outnumbers nonfiction about five to
// one, which feels right for a seaside bookshop.
const ALL_BOOKS = BOOKS.concat(NONFICTION);
